name: echo_52hz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
